name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"   # يحدث مرة يوميًا (الساعة 06:00 UTC)
  workflow_dispatch:       # تشغيل يدوي من تبويب Actions

permissions:
  contents: write          # يسمح للـ Action يكتب الملف داخل الريبو

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}            # السر الذي أنشأته
          user: muhammadshurman                  # <-- اسم المستخدم تبعك
          template: classic
          filename: metrics.svg                  # اسم الملف الناتج
          base: header, repositories, activity   # أقسام أساسية
          repositories_affiliations: owner, collaborator
          config_timezone: Asia/Amman

          # إضافات مفيدة
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_ignored: html, css

          # لو بدك تحسب الخاص كأرقام عامة (يلزم PAT بصلاحية repo)
          # لاحظ: لعرض "مساهمات خاصة" لازم تفعلها من إعدادات GitHub (انظر خطوة 3)
          commits_authoring: muhammadshurman
