name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"     # يوميًّا 06:00 UTC
  workflow_dispatch:         # تشغيل يدوي

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          user: muhammadshurman

          # أين و كيف يحفظ الناتج
          filename: metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"
          config_timezone: Asia/Amman

          # عرض الأرقام التي تهمّك (كل الزمن)
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          # نشاط إضافي إن رغبت
          plugin_activity: yes
          plugin_activity_filter: all
          plugin_activity_days: 3650   # ~10 سنوات
