name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          user: muhammadshurman
          template: classic
          filename: metrics.svg
          base: header
          config_timezone: Asia/Amman
          
          # إظهار إحصائيات المتابعة والمساهمات من بداية الحساب
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          plugin_activity: yes
          plugin_activity_limit: 100
          plugin_activity_days: 3650   # 10 سنوات للخلف
          plugin_activity_filter: all
